name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Extract Project
        run: tar -xf zaz-pos-pro.tar

      - name: Install Dependencies
        run: |
          cd zaz-pos-pro
          npm install

      - name: Fix package.json
        run: |
          cd zaz-pos-pro
          npm install electron --save-dev
          npm install electron-builder --save-dev

      - name: Build EXE
        run: |
          cd zaz-pos-pro
          npx electron-builder --win --publish=never

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe-file
          path: zaz-pos-pro/dist/
